// Auto-generated from deployments/sepolia/ShadowBallot.json
export const shadowBallotAbi = [
  { inputs: [], name: 'AlreadyVoted', type: 'error' },
  { inputs: [], name: 'CleartextPayloadMismatch', type: 'error' },
  { inputs: [], name: 'CleartextValueOverflow', type: 'error' },
  { inputs: [], name: 'EmptyPollName', type: 'error' },
  { inputs: [], name: 'InvalidBallot', type: 'error' },
  { inputs: [], name: 'InvalidKMSSignatures', type: 'error' },
  { inputs: [], name: 'InvalidOptionCount', type: 'error' },
  { inputs: [], name: 'InvalidOptionLabel', type: 'error' },
  { inputs: [], name: 'InvalidPoll', type: 'error' },
  { inputs: [], name: 'InvalidSchedule', type: 'error' },
  { inputs: [], name: 'PollAlreadyFinalized', type: 'error' },
  { inputs: [], name: 'PollAlreadyPublished', type: 'error' },
  { inputs: [], name: 'PollNotActive', type: 'error' },
  { inputs: [], name: 'PollNotFinalized', type: 'error' },
  { inputs: [], name: 'ZamaProtocolUnsupported', type: 'error' },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { indexed: false, internalType: 'string', name: 'name', type: 'string' },
      { indexed: false, internalType: 'uint64', name: 'startTime', type: 'uint64' },
      { indexed: false, internalType: 'uint64', name: 'endTime', type: 'uint64' },
    ],
    name: 'PollCreated',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'caller', type: 'address' },
    ],
    name: 'PollFinalized',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: false, internalType: 'bytes32[]', name: 'handlesList', type: 'bytes32[]' },
      { indexed: false, internalType: 'bytes', name: 'abiEncodedCleartexts', type: 'bytes' },
    ],
    name: 'PublicDecryptionVerified',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { indexed: false, internalType: 'uint32[]', name: 'results', type: 'uint32[]' },
    ],
    name: 'ResultsPublished',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      { indexed: true, internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { indexed: true, internalType: 'address', name: 'voter', type: 'address' },
    ],
    name: 'VoteSubmitted',
    type: 'event',
  },
  {
    inputs: [],
    name: 'confidentialProtocolId',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'string[]', name: 'options', type: 'string[]' },
      { internalType: 'uint64', name: 'startTime', type: 'uint64' },
      { internalType: 'uint64', name: 'endTime', type: 'uint64' },
    ],
    name: 'createPoll',
    outputs: [{ internalType: 'uint256', name: 'pollId', type: 'uint256' }],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'pollId', type: 'uint256' }],
    name: 'finalizePoll',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'pollId', type: 'uint256' }],
    name: 'getEncryptedTallies',
    outputs: [{ internalType: 'euint32[]', name: '', type: 'bytes32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'pollId', type: 'uint256' }],
    name: 'getPoll',
    outputs: [
      { internalType: 'string', name: 'name', type: 'string' },
      { internalType: 'string', name: 'description', type: 'string' },
      { internalType: 'string[]', name: 'options', type: 'string[]' },
      { internalType: 'uint64', name: 'startTime', type: 'uint64' },
      { internalType: 'uint64', name: 'endTime', type: 'uint64' },
      { internalType: 'address', name: 'creator', type: 'address' },
      { internalType: 'bool', name: 'finalized', type: 'bool' },
      { internalType: 'bool', name: 'resultsPublished', type: 'bool' },
      { internalType: 'uint64', name: 'createdAt', type: 'uint64' },
      { internalType: 'uint64', name: 'finalizedAt', type: 'uint64' },
      { internalType: 'uint64', name: 'publishedAt', type: 'uint64' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'getPollCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: 'pollId', type: 'uint256' }],
    name: 'getPublishedResults',
    outputs: [{ internalType: 'uint32[]', name: '', type: 'uint32[]' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { internalType: 'address', name: 'account', type: 'address' },
    ],
    name: 'hasUserVoted',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { internalType: 'bytes', name: 'abiEncodedCleartexts', type: 'bytes' },
      { internalType: 'bytes', name: 'decryptionProof', type: 'bytes' },
    ],
    name: 'publishResults',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: 'pollId', type: 'uint256' },
      { internalType: 'externalEuint32[]', name: 'encryptedBallot', type: 'bytes32[]' },
      { internalType: 'bytes', name: 'inputProof', type: 'bytes' },
    ],
    name: 'vote',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
] as const;
